# postgreSQLの設定
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/sslcert?serverTimezone=JST&characterEncoding=utf8
    username: postgres
    password: ${SPRING_PROPERTY_PASSWORD}

# 次の記述がないと、Spring Boot 2.1.xでは動くが、Spring Boot 2.2.0では動かない
  mvc:
    hiddenmethod:
      filter:
        enabled:  true

# Mybatisの設定
# 自動的にDB上のアンダースコア文字列とDtoのキャメルケース文字列をマッピング
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout:  30

# SPRINGメールプロパティ
  mail:
    default-encoding: ISO-2022-JP
    host: email-smtp.ap-northeast-1.amazonaws.com
    port: 465
    protocol: smtps
    username: ${AWS_ACCESS_KEY_ID}
    password: ${AWS_SECRET_ACCESS_KEY}
    smtps:
      auth: true
    smtp:
      ssl:
        enable: true
        
mail:
  smtps:
    auth: true
  smtp:
    starttls:
      enable: true
  transport:
    protocol: smtps
  connectiontimeout:  1000
  timeout:  1000
  debug:  true
  to: asano@jprs.co.jp
  cc: space.888pq@gmail.com
  from: no-reply@az.jprs.co.jp  
            
# log file
app:
  path: log/
  logFilePrefix:  sslcert-G3.log.

# mail
mail:
  to: asano@jprs.co.jp
  cc: space.888pq@gmail.com
  from: no-reply@az.jprs.co.jp

# logging
logging:
  level:
    org:
      springframework:
        web:  INFO
  file: log/console.log

# AWS
cloud:
  aws:
    credentials:
      accessKey:  ${AWS_ACCESS_KEY_ID}
      secretKey:  ${AWS_SECRET_ACCESS_KEY}
    region:
      auto: true
    stack:
      auto: true
